### ISSUE TITLE
ListTags seem to be broken

### ISSUE THREAD

**Issue by BJTMastermind** [BJTMastermind/go-nbt#1]
ListTags when written to file seem to always be empty when constructed like this in a compound:

```go
"List Name": &nbt.List{
    Value: []nbt.Tag{
        &nbt.Short{
            Value: 100,
        },
    },
}
```
- [ ] Verify if this is broken or if im doing something wrong.
- [ ] If broken, Fix whats causing it
- [ ] Add ListTag example to `main.go` regardless

**Comment by VoxelBill** [comment]
Looks like i was doing something wrong. The correct format is:
```go
"List Name": &nbt.List{
    Value: []nbt.Tag{
        &nbt.Short{
            Value: 100,
        },
    },
    ListType: nbt.IDTagShort,
}
```
